'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

type Entry = { at: number; ok: boolean; payer?: string; amount: string; tx?: string; error?: string };
type Data = { merchant: string; evil: boolean; payTo: string; price: string; net: { name: string; chainId: number; explorer: string; xsgd: string }; entries: Entry[] };
const sgd = (a: string) => (Number(a) / 1e6).toFixed(2);
const short = (s?: string) => s ? `${s.slice(0, 6)}…${s.slice(-4)}` : '—';

export default function MerchantPage() {
  const [d,setD] = useState<Data|null>(null);
  useEffect(()=>{const load=()=>fetch('/api/history').then(r=>r.json()).then(setD).catch(()=>{});load();const t=setInterval(load,1500);return()=>clearInterval(t)},[]);
  if(!d) return <main className="loading">loading merchant ledger…</main>;
  return <main className="merchant"><nav><Link href="/" className="brand">sponsored<span>compute</span></Link><div><Link href="/sponsor">Sponsor</Link><span>MERCHANT / {d.net.chainId}</span></div></nav><header><p>MERCHANT CONSOLE · x402 RECEIVER</p><h1>{d.merchant}<em>.</em></h1><span className={d.evil?'bad':'live'}>{d.evil?'UNTRUSTED CHALLENGE':'ALLOWLISTED MERCHANT'}</span></header><section className="stats"><div><small>PRICE / CALL</small><b>{sgd(d.price)} XSGD</b></div><div><small>API ENDPOINT</small><code>POST /api/v1/query</code></div><div><small>PAY TO</small><code>{short(d.payTo)}</code></div></section>{d.evil&&<aside>Challenge includes a prompt-injection instruction. The agent checkpoint rejects it before unwrap or signature.</aside>}<section className="ledger"><div><p>SETTLEMENT LEDGER</p><small>Realtime view · server instance history</small></div>{d.entries.length===0?<p className="empty">No payment yet. The first valid x402 request will appear here.</p>:<div className="rows">{d.entries.map((e,i)=><div key={i}><span>{e.ok?'✓':'×'}</span><time>{new Date(e.at).toLocaleTimeString()}</time><code>{short(e.payer)}</code><b>{sgd(e.amount)} XSGD</b>{e.tx?<a href={e.tx} target="_blank">Snowtrace ↗</a>:<em>{e.error}</em>}</div>)}</div>}</section><style jsx>{`
  :global(body){margin:0;background:#0d0f0b;color:#f4f6ed;font-family:'Helvetica Neue',Helvetica,sans-serif}.merchant,.loading{min-height:100vh;padding:0 4.5vw 80px;background:radial-gradient(ellipse 65% 40% at 100% 0%,#21331c 0%,#0d0f0b 70%)}nav{height:76px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #354031;font:11px ui-monospace,monospace;letter-spacing:.08em}.brand{font:800 17px 'Helvetica Neue';letter-spacing:-.07em;color:#f4f6ed;text-decoration:none}.brand span,header p,header em,.live{color:#c8ff45}nav div{display:flex;gap:22px;align-items:center;color:#aeb8a8}nav a{color:#dce7d5;text-decoration:none}header{padding:80px 0 42px}header p,.stats small,.ledger p{font:700 11px ui-monospace,monospace;letter-spacing:.1em}header h1{font-size:clamp(58px,10vw,130px);letter-spacing:-.09em;line-height:.8;margin:16px 0 30px}header em{font-style:normal}.live,.bad{font:11px ui-monospace,monospace}.bad{color:#ff8e83}.stats{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #3e4939;border-bottom:1px solid #3e4939}.stats div{padding:24px 24px 24px 0}.stats div+div{padding-left:24px;border-left:1px solid #3e4939}.stats small{display:block;color:#8b9784;margin-bottom:12px}.stats b{font-size:25px;color:#c8ff45}.stats code{font:13px ui-monospace,monospace;color:#dce7d5}aside{margin-top:22px;padding:16px;border-left:3px solid #ff8e83;background:#291715;color:#ffd7d2;line-height:1.5}.ledger{margin-top:58px;border:1px solid #3e4939;background:#131811}.ledger>div:first-child{padding:22px;border-bottom:1px solid #3e4939}.ledger p{margin:0 0 6px;color:#c8ff45}.ledger small{color:#8b9784}.empty{padding:36px 22px;color:#aeb8a8}.rows>div{display:grid;grid-template-columns:30px 120px 1fr 140px 130px;gap:12px;padding:16px 22px;border-bottom:1px solid #2e382a;align-items:center;font-size:13px}.rows span{color:#c8ff45;font-size:18px}.rows time,.rows code{color:#aeb8a8;font:11px ui-monospace,monospace}.rows b{color:#f4f6ed}.rows a{color:#c8ff45;text-decoration:none}.rows em{font-style:normal;color:#ff8e83}.loading{display:grid;place-items:center;color:#c8ff45;font:13px ui-monospace,monospace}@media(max-width:700px){.stats{grid-template-columns:1fr}.stats div+div{padding-left:0;border-left:0;border-top:1px solid #3e4939}.rows>div{grid-template-columns:25px 1fr;gap:8px}.rows time{grid-column:2}.rows code,.rows b,.rows a,.rows em{grid-column:2}nav div{gap:10px}}
`}</style></main>;
}
